class_name PokemonsEnum

# IDs de PokeAPI para Kanto (1-151)
enum Values {
	NONE = 0,
	BULBASAUR = 1,
	IVYSAUR = 2,
	VENUSAUR = 3,
	CHARMANDER = 4,
	CHARMELEON = 5,
	CHARIZARD = 6,
	SQUIRTLE = 7,
	WARTORTLE = 8,
	BLASTOISE = 9,
	CATERPIE = 10,
	METAPOD = 11,
	BUTTERFREE = 12,
	WEEDLE = 13,
	KAKUNA = 14,
	BEEDRILL = 15,
	PIDGEY = 16,
	PIDGEOTTO = 17,
	PIDGEOT = 18,
	RATTATA = 19,
	RATICATE = 20,
	SPEAROW = 21,
	FEAROW = 22,
	EKANS = 23,
	ARBOK = 24,
	PIKACHU = 25,
	RAICHU = 26,
	SANDSHREW = 27,
	SANDSLASH = 28,
	NIDORAN_F = 29,
	NIDORINA = 30,
	NIDOQUEEN = 31,
	NIDORAN_M = 32,
	NIDORINO = 33,
	NIDOKING = 34,
	CLEFAIRY = 35,
	CLEFABLE = 36,
	VULPIX = 37,
	NINETALES = 38,
	JIGGLYPUFF = 39,
	WIGGLYTUFF = 40,
	ZUBAT = 41,
	GOLBAT = 42,
	ODDISH = 43,
	GLOOM = 44,
	VILEPLUME = 45,
	PARAS = 46,
	PARASECT = 47,
	VENONAT = 48,
	VENOMOTH = 49,
	DIGLETT = 50,
	DUGTRIO = 51,
	MEOWTH = 52,
	PERSIAN = 53,
	PSYDUCK = 54,
	GOLDUCK = 55,
	MANKEY = 56,
	PRIMEAPE = 57,
	GROWLITHE = 58,
	ARCANINE = 59,
	POLIWAG = 60,
	POLIWHIRL = 61,
	POLIWRATH = 62,
	ABRA = 63,
	KADABRA = 64,
	ALAKAZAM = 65,
	MACHOP = 66,
	MACHOKE = 67,
	MACHAMP = 68,
	BELLSPROUT = 69,
	WEEPINBELL = 70,
	VICTREEBEL = 71,
	TENTACOOL = 72,
	TENTACRUEL = 73,
	GEODUDE = 74,
	GRAVELER = 75,
	GOLEM = 76,
	PONYTA = 77,
	RAPIDASH = 78,
	SLOWPOKE = 79,
	SLOWBRO = 80,
	MAGNEMITE = 81,
	MAGNETON = 82,
	FARFETCHD = 83,
	DODUO = 84,
	DODRIO = 85,
	SEEL = 86,
	DEWGONG = 87,
	GRIMER = 88,
	MUK = 89,
	SHELLDER = 90,
	CLOYSTER = 91,
	GASTLY = 92,
	HAUNTER = 93,
	GENGAR = 94,
	ONIX = 95,
	DROWZEE = 96,
	HYPNO = 97,
	KRABBY = 98,
	KINGLER = 99,
	VOLTORB = 100,
	ELECTRODE = 101,
	EXEGGCUTE = 102,
	EXEGGUTOR = 103,
	CUBONE = 104,
	MAROWAK = 105,
	HITMONLEE = 106,
	HITMONCHAN = 107,
	LICKITUNG = 108,
	KOFFING = 109,
	WEEZING = 110,
	RHYHORN = 111,
	RHYDON = 112,
	CHANSEY = 113,
	TANGELA = 114,
	KANGASKHAN = 115,
	HORSEA = 116,
	SEADRA = 117,
	GOLDEEN = 118,
	SEAKING = 119,
	STARYU = 120,
	STARMIE = 121,
	MR_MIME = 122, # Mr. Mime (ID 122)
	SCYTHER = 123,
	JYNX = 124,
	ELECTABUZZ = 125,
	MAGMAR = 126,
	PINSIR = 127,
	TAUROS = 128,
	MAGIKARP = 129,
	GYARADOS = 130,
	LAPRAS = 131,
	DITTO = 132,
	EEVEE = 133,
	VAPOREON = 134,
	JOLTEON = 135,
	FLAREON = 136,
	PORYGON = 137,
	OMANYTE = 138,
	OMASTAR = 139,
	KABUTO = 140,
	KABUTOPS = 141,
	AERODACTYL = 142,
	SNORLAX = 143,
	ARTICUNO = 144,
	ZAPDOS = 145,
	MOLTRES = 146,
	DRATINI = 147,
	DRAGONAIR = 148,
	DRAGONITE = 149,
	MEWTWO = 150,
	MEW = 151,
}

static func from_string(name: String) -> int:
	var key := name.to_lower()
	match key:
		"bulbasaur": return Values.BULBASAUR
		"ivysaur": return Values.IVYSAUR
		"venusaur": return Values.VENUSAUR
		"charmander": return Values.CHARMANDER
		"charmeleon": return Values.CHARMELEON
		"charizard": return Values.CHARIZARD
		"squirtle": return Values.SQUIRTLE
		"wartortle": return Values.WARTORTLE
		"blastoise": return Values.BLASTOISE
		# ... (continúa según sea necesario)
		_: return Values.NONE

## Convierte un valor del enum a su nombre legible
static func get_display_name(pokemon_id: Values) -> String:
	match pokemon_id:
		Values.NONE: return "Ninguno"
		Values.BULBASAUR: return "Bulbasaur"
		Values.IVYSAUR: return "Ivysaur"
		Values.VENUSAUR: return "Venusaur"
		Values.CHARMANDER: return "Charmander"
		Values.CHARMELEON: return "Charmeleon"
		Values.CHARIZARD: return "Charizard"
		Values.SQUIRTLE: return "Squirtle"
		Values.WARTORTLE: return "Wartortle"
		Values.BLASTOISE: return "Blastoise"
		Values.CATERPIE: return "Caterpie"
		Values.METAPOD: return "Metapod"
		Values.BUTTERFREE: return "Butterfree"
		Values.WEEDLE: return "Weedle"
		Values.KAKUNA: return "Kakuna"
		Values.BEEDRILL: return "Beedrill"
		Values.PIDGEY: return "Pidgey"
		Values.PIDGEOTTO: return "Pidgeotto"
		Values.PIDGEOT: return "Pidgeot"
		Values.RATTATA: return "Rattata"
		Values.RATICATE: return "Raticate"
		Values.SPEAROW: return "Spearow"
		Values.FEAROW: return "Fearow"
		Values.EKANS: return "Ekans"
		Values.ARBOK: return "Arbok"
		Values.PIKACHU: return "Pikachu"
		Values.RAICHU: return "Raichu"
		Values.SANDSHREW: return "Sandshrew"
		Values.SANDSLASH: return "Sandslash"
		Values.NIDORAN_F: return "Nidoran♀"
		Values.NIDORINA: return "Nidorina"
		Values.NIDOQUEEN: return "Nidoqueen"
		Values.NIDORAN_M: return "Nidoran♂"
		Values.NIDORINO: return "Nidorino"
		Values.NIDOKING: return "Nidoking"
		Values.CLEFAIRY: return "Clefairy"
		Values.CLEFABLE: return "Clefable"
		Values.VULPIX: return "Vulpix"
		Values.NINETALES: return "Ninetales"
		Values.JIGGLYPUFF: return "Jigglypuff"
		Values.WIGGLYTUFF: return "Wigglytuff"
		Values.ZUBAT: return "Zubat"
		Values.GOLBAT: return "Golbat"
		Values.ODDISH: return "Oddish"
		Values.GLOOM: return "Gloom"
		Values.VILEPLUME: return "Vileplume"
		Values.PARAS: return "Paras"
		Values.PARASECT: return "Parasect"
		Values.VENONAT: return "Venonat"
		Values.VENOMOTH: return "Venomoth"
		Values.DIGLETT: return "Diglett"
		Values.DUGTRIO: return "Dugtrio"
		Values.MEOWTH: return "Meowth"
		Values.PERSIAN: return "Persian"
		Values.PSYDUCK: return "Psyduck"
		Values.GOLDUCK: return "Golduck"
		Values.MANKEY: return "Mankey"
		Values.PRIMEAPE: return "Primeape"
		Values.GROWLITHE: return "Growlithe"
		Values.ARCANINE: return "Arcanine"
		Values.POLIWAG: return "Poliwag"
		Values.POLIWHIRL: return "Poliwhirl"
		Values.POLIWRATH: return "Poliwrath"
		Values.ABRA: return "Abra"
		Values.KADABRA: return "Kadabra"
		Values.ALAKAZAM: return "Alakazam"
		Values.MACHOP: return "Machop"
		Values.MACHOKE: return "Machoke"
		Values.MACHAMP: return "Machamp"
		Values.BELLSPROUT: return "Bellsprout"
		Values.WEEPINBELL: return "Weepinbell"
		Values.VICTREEBEL: return "Victreebel"
		Values.TENTACOOL: return "Tentacool"
		Values.TENTACRUEL: return "Tentacruel"
		Values.GEODUDE: return "Geodude"
		Values.GRAVELER: return "Graveler"
		Values.GOLEM: return "Golem"
		Values.PONYTA: return "Ponyta"
		Values.RAPIDASH: return "Rapidash"
		Values.SLOWPOKE: return "Slowpoke"
		Values.SLOWBRO: return "Slowbro"
		Values.MAGNEMITE: return "Magnemite"
		Values.MAGNETON: return "Magneton"
		Values.FARFETCHD: return "Farfetch'd"
		Values.DODUO: return "Doduo"
		Values.DODRIO: return "Dodrio"
		Values.SEEL: return "Seel"
		Values.DEWGONG: return "Dewgong"
		Values.GRIMER: return "Grimer"
		Values.MUK: return "Muk"
		Values.SHELLDER: return "Shellder"
		Values.CLOYSTER: return "Cloyster"
		Values.GASTLY: return "Gastly"
		Values.HAUNTER: return "Haunter"
		Values.GENGAR: return "Gengar"
		Values.ONIX: return "Onix"
		Values.DROWZEE: return "Drowzee"
		Values.HYPNO: return "Hypno"
		Values.KRABBY: return "Krabby"
		Values.KINGLER: return "Kingler"
		Values.VOLTORB: return "Voltorb"
		Values.ELECTRODE: return "Electrode"
		Values.EXEGGCUTE: return "Exeggcute"
		Values.EXEGGUTOR: return "Exeggutor"
		Values.CUBONE: return "Cubone"
		Values.MAROWAK: return "Marowak"
		Values.HITMONLEE: return "Hitmonlee"
		Values.HITMONCHAN: return "Hitmonchan"
		Values.LICKITUNG: return "Lickitung"
		Values.KOFFING: return "Koffing"
		Values.WEEZING: return "Weezing"
		Values.RHYHORN: return "Rhyhorn"
		Values.RHYDON: return "Rhydon"
		Values.CHANSEY: return "Chansey"
		Values.TANGELA: return "Tangela"
		Values.KANGASKHAN: return "Kangaskhan"
		Values.HORSEA: return "Horsea"
		Values.SEADRA: return "Seadra"
		Values.GOLDEEN: return "Goldeen"
		Values.SEAKING: return "Seaking"
		Values.STARYU: return "Staryu"
		Values.STARMIE: return "Starmie"
		Values.MR_MIME: return "Mr. Mime"
		Values.SCYTHER: return "Scyther"
		Values.JYNX: return "Jynx"
		Values.ELECTABUZZ: return "Electabuzz"
		Values.MAGMAR: return "Magmar"
		Values.PINSIR: return "Pinsir"
		Values.TAUROS: return "Tauros"
		Values.MAGIKARP: return "Magikarp"
		Values.GYARADOS: return "Gyarados"
		Values.LAPRAS: return "Lapras"
		Values.DITTO: return "Ditto"
		Values.EEVEE: return "Eevee"
		Values.VAPOREON: return "Vaporeon"
		Values.JOLTEON: return "Jolteon"
		Values.FLAREON: return "Flareon"
		Values.PORYGON: return "Porygon"
		Values.OMANYTE: return "Omanyte"
		Values.OMASTAR: return "Omastar"
		Values.KABUTO: return "Kabuto"
		Values.KABUTOPS: return "Kabutops"
		Values.AERODACTYL: return "Aerodactyl"
		Values.SNORLAX: return "Snorlax"
		Values.ARTICUNO: return "Articuno"
		Values.ZAPDOS: return "Zapdos"
		Values.MOLTRES: return "Moltres"
		Values.DRATINI: return "Dratini"
		Values.DRAGONAIR: return "Dragonair"
		Values.DRAGONITE: return "Dragonite"
		Values.MEWTWO: return "Mewtwo"
		Values.MEW: return "Mew"
		_: return "Pokemon #%d" % pokemon_id
